name: Python application test with GitHub Actions

on: 
  push:
    branches:
      - main  # Only trigger on push to the main branch

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.12.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.5
    
    - name: Install dependencies
      run: |
        make install
    
    - name: Install additional tools
      run: |
        make post-install
    
    - name: Lint with pylint
      run: |
        make lint
    
    - name: Test with pytest
      run: |
        make test
    
    - name: Format code
      run: |
        make format
    
    - name: Build the Docker image
      run: |
        make build
        
  deploy:
    needs: build  # Ensure deploy runs only after build is successful
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 247181180961.dkr.ecr.sa-east-1.amazonaws.com

    - name: Push Docker image
      run: |
        docker push 247181180961.dkr.ecr.sa-east-1.amazonaws.com/myecr-repo:latest
    
    - name: Log out from ECR
      run: docker logout 247181180961.dkr.ecr.sa-east-1.amazonaws.com